// Auto-generated from channel-list-20250114.pdf
// Fields: channelNo, name, hdSd, genre, epgNo
// FTA/Pay, MRP columns intentionally omitted

const CHANNEL_REFERENCE = [
  // ── Hindi Entertainment ──────────────────────────────────────
  { channelNo: 1,  name: "Star Plus",                     hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 115 },
  { channelNo: 2,  name: "Star Plus",                     hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 117 },
  { channelNo: 3,  name: "Star Bharat",                   hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 121 },
  { channelNo: 4,  name: "Star Bharat",                   hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 122 },
  { channelNo: 5,  name: "Sony Entertainment Television", hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 128 },
  { channelNo: 6,  name: "Sony Entertainment Television", hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 130 },
  { channelNo: 7,  name: "Sony SAB",                      hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 132 },
  { channelNo: 8,  name: "Sony SAB",                      hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 134 },
  { channelNo: 9,  name: "&TV",                           hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 137 },
  { channelNo: 10, name: "&TV",                           hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 139 },
  { channelNo: 11, name: "Zee TV",                        hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 141 },
  { channelNo: 12, name: "Zee TV",                        hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 143 },
  { channelNo: 13, name: "Colors",                        hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 147 },
  { channelNo: 14, name: "Colors",                        hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 149 },
  { channelNo: 15, name: "Bindass",                       hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 153 },
  { channelNo: 16, name: "Investigation Discovery",       hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 155 },
  { channelNo: 17, name: "Investigation Discovery",       hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 156 },
  { channelNo: 18, name: "Star Utsav",                    hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 171 },
  { channelNo: 19, name: "Zee Anmol",                     hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 172 },
  { channelNo: 20, name: "Colors Rishtey",                hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 173 },
  { channelNo: 21, name: "Sony Pal",                      hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 174 },
  { channelNo: 22, name: "The Q",                         hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 175 },
  { channelNo: 23, name: "Big Magic",                     hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 176 },
  { channelNo: 24, name: "Dangal",                        hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 177 },
  { channelNo: 25, name: "Anjan TV",                      hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 178 },
  { channelNo: 26, name: "Shemaroo TV",                   hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 181 },
  { channelNo: 27, name: "Ishara",                        hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 182 },
  { channelNo: 28, name: "Dangal 2",                      hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 183 },
  { channelNo: 29, name: "Shemaroo UMANG",                hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 184 },
  { channelNo: 30, name: "NAZARA",                        hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 185 },
  { channelNo: 31, name: "Manoranjan Grand",              hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 187 },
  { channelNo: 32, name: "Sun Neo",                       hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 189 },
  { channelNo: 33, name: "Sun Neo",                       hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 190 },
  { channelNo: 34, name: "DD National",                   hdSd: "HD", genre: "Hindi Entertainment",    epgNo: 196 },
  { channelNo: 35, name: "DD National",                   hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 197 },
  { channelNo: 36, name: "DD Kisan",                      hdSd: "SD", genre: "Hindi Entertainment",    epgNo: 198 },
  // ── English Entertainment ─────────────────────────────────────
  { channelNo: 37, name: "Zee Café",                      hdSd: "HD", genre: "English Entertainment",  epgNo: 210 },
  { channelNo: 38, name: "Zee Café",                      hdSd: "SD", genre: "English Entertainment",  epgNo: 211 },
  { channelNo: 39, name: "Colors Infinity",               hdSd: "HD", genre: "English Entertainment",  epgNo: 214 },
  { channelNo: 40, name: "Colors Infinity",               hdSd: "SD", genre: "English Entertainment",  epgNo: 215 },
  { channelNo: 41, name: "Comedy Central",                hdSd: "HD", genre: "English Entertainment",  epgNo: 218 },
  { channelNo: 42, name: "Comedy Central",                hdSd: "SD", genre: "English Entertainment",  epgNo: 219 },
  { channelNo: 43, name: "Disney International",          hdSd: "HD", genre: "English Entertainment",  epgNo: 221 },
  // ── Hindi Movies ─────────────────────────────────────────────
  { channelNo: 44, name: "Star Gold",                     hdSd: "HD", genre: "Hindi Movies",           epgNo: 308 },
  { channelNo: 45, name: "Star Gold",                     hdSd: "SD", genre: "Hindi Movies",           epgNo: 310 },
  { channelNo: 46, name: "Sony Max",                      hdSd: "HD", genre: "Hindi Movies",           epgNo: 312 },
  { channelNo: 47, name: "Sony Max",                      hdSd: "SD", genre: "Hindi Movies",           epgNo: 314 },
  { channelNo: 48, name: "Star Gold 2",                   hdSd: "HD", genre: "Hindi Movies",           epgNo: 316 },
  { channelNo: 49, name: "Star Gold 2",                   hdSd: "SD", genre: "Hindi Movies",           epgNo: 317 },
  { channelNo: 50, name: "Zee Cinema",                    hdSd: "HD", genre: "Hindi Movies",           epgNo: 319 },
  { channelNo: 51, name: "Zee Cinema",                    hdSd: "SD", genre: "Hindi Movies",           epgNo: 321 },
  { channelNo: 52, name: "Star Gold Romance",             hdSd: "SD", genre: "Hindi Movies",           epgNo: 323 },
  { channelNo: 53, name: "Star Gold Thrills",             hdSd: "SD", genre: "Hindi Movies",           epgNo: 325 },
  { channelNo: 54, name: "Zee Bollywood",                 hdSd: "SD", genre: "Hindi Movies",           epgNo: 327 },
  { channelNo: 55, name: "Zee Classic",                   hdSd: "SD", genre: "Hindi Movies",           epgNo: 328 },
  { channelNo: 56, name: "&pictures",                     hdSd: "HD", genre: "Hindi Movies",           epgNo: 331 },
  { channelNo: 57, name: "&pictures",                     hdSd: "SD", genre: "Hindi Movies",           epgNo: 332 },
  { channelNo: 58, name: "&Xplor",                        hdSd: "HD", genre: "Hindi Movies",           epgNo: 333 },
  { channelNo: 59, name: "Colors Cineplex",               hdSd: "HD", genre: "Hindi Movies",           epgNo: 344 },
  { channelNo: 60, name: "Colors Cineplex",               hdSd: "SD", genre: "Hindi Movies",           epgNo: 345 },
  { channelNo: 61, name: "B4U Kadak",                     hdSd: "SD", genre: "Hindi Movies",           epgNo: 346 },
  { channelNo: 62, name: "Action Cinema",                 hdSd: "SD", genre: "Hindi Movies",           epgNo: 349 },
  { channelNo: 63, name: "Sony Wah",                      hdSd: "SD", genre: "Hindi Movies",           epgNo: 351 },
  { channelNo: 64, name: "B4U Movies",                    hdSd: "SD", genre: "Hindi Movies",           epgNo: 352 },
  { channelNo: 65, name: "Sony Max 2",                    hdSd: "SD", genre: "Hindi Movies",           epgNo: 355 },
  { channelNo: 66, name: "Star Gold Select",              hdSd: "HD", genre: "Hindi Movies",           epgNo: 356 },
  { channelNo: 67, name: "Star Gold Select",              hdSd: "SD", genre: "Hindi Movies",           epgNo: 357 },
  { channelNo: 68, name: "Wow Cinema One",                hdSd: "SD", genre: "Hindi Movies",           epgNo: 365 },
  { channelNo: 69, name: "BFLIX",                         hdSd: "SD", genre: "Hindi Movies",           epgNo: 367 },
  { channelNo: 70, name: "Star Utsav Movies",             hdSd: "SD", genre: "Hindi Movies",           epgNo: 369 },
  { channelNo: 71, name: "Zee Anmol Cinema",              hdSd: "SD", genre: "Hindi Movies",           epgNo: 371 },
  { channelNo: 72, name: "Colors Cineplex Superhits",     hdSd: "SD", genre: "Hindi Movies",           epgNo: 372 },
  { channelNo: 73, name: "Colors Cineplex Bollywood",     hdSd: "SD", genre: "Hindi Movies",           epgNo: 373 },
  { channelNo: 74, name: "All Time Movies",               hdSd: "SD", genre: "Hindi Movies",           epgNo: 374 },
  { channelNo: 75, name: "Goldmines",                     hdSd: "SD", genre: "Hindi Movies",           epgNo: 375 },
  { channelNo: 76, name: "Manoranjan TV",                 hdSd: "SD", genre: "Hindi Movies",           epgNo: 376 },
  { channelNo: 77, name: "Zee Anmol Cinema 2",            hdSd: "SD", genre: "Hindi Movies",           epgNo: 377 },
  { channelNo: 78, name: "Chumbak TV",                    hdSd: "SD", genre: "Hindi Movies",           epgNo: 383 },
  { channelNo: 79, name: "Manoranjan Prime",              hdSd: "SD", genre: "Hindi Movies",           epgNo: 384 },
  // ── English Movies ────────────────────────────────────────────
  { channelNo: 80, name: "Star Movies",                   hdSd: "HD", genre: "English Movies",         epgNo: 402 },
  { channelNo: 81, name: "Star Movies",                   hdSd: "SD", genre: "English Movies",         epgNo: 403 },
  { channelNo: 82, name: "Sony Pix",                      hdSd: "HD", genre: "English Movies",         epgNo: 406 },
  { channelNo: 83, name: "Sony Pix",                      hdSd: "SD", genre: "English Movies",         epgNo: 407 },
  { channelNo: 84, name: "&flix",                         hdSd: "HD", genre: "English Movies",         epgNo: 412 },
  { channelNo: 85, name: "&flix",                         hdSd: "SD", genre: "English Movies",         epgNo: 413 },
  { channelNo: 86, name: "Star Movies Select",            hdSd: "HD", genre: "English Movies",         epgNo: 418 },
  { channelNo: 87, name: "Star Movies Select",            hdSd: "SD", genre: "English Movies",         epgNo: 419 },
  { channelNo: 88, name: "Movies Now",                    hdSd: "HD", genre: "English Movies",         epgNo: 420 },
  { channelNo: 89, name: "Movies Now",                    hdSd: "SD", genre: "English Movies",         epgNo: 421 },
  { channelNo: 90, name: "MN+",                           hdSd: "HD", genre: "English Movies",         epgNo: 423 },
  { channelNo: 91, name: "MNX",                           hdSd: "HD", genre: "English Movies",         epgNo: 425 },
  { channelNo: 92, name: "MNX",                           hdSd: "SD", genre: "English Movies",         epgNo: 426 },
  { channelNo: 93, name: "Romedy Now",                    hdSd: "SD", genre: "English Movies",         epgNo: 429 },
  { channelNo: 94, name: "&prive",                        hdSd: "HD", genre: "English Movies",         epgNo: 431 },
  // ── Sports ────────────────────────────────────────────────────
  { channelNo: 95,  name: "DD Sports",                    hdSd: "HD", genre: "Sports",                 epgNo: 452 },
  { channelNo: 96,  name: "DD Sports",                    hdSd: "SD", genre: "Sports",                 epgNo: 453 },
  { channelNo: 97,  name: "Star Sports 1",                hdSd: "HD", genre: "Sports",                 epgNo: 454 },
  { channelNo: 98,  name: "Star Sports 1",                hdSd: "SD", genre: "Sports",                 epgNo: 455 },
  { channelNo: 99,  name: "Star Sports 2",                hdSd: "HD", genre: "Sports",                 epgNo: 456 },
  { channelNo: 100, name: "Star Sports 2",                hdSd: "SD", genre: "Sports",                 epgNo: 457 },
  { channelNo: 101, name: "Star Sports 3",                hdSd: "SD", genre: "Sports",                 epgNo: 458 },
  { channelNo: 102, name: "Star Sports 1 Hindi",          hdSd: "HD", genre: "Sports",                 epgNo: 459 },
  { channelNo: 103, name: "Star Sports 1 Hindi",          hdSd: "SD", genre: "Sports",                 epgNo: 460 },
  { channelNo: 104, name: "Star Sports Select 1",         hdSd: "HD", genre: "Sports",                 epgNo: 463 },
  { channelNo: 105, name: "Star Sports Select 1",         hdSd: "SD", genre: "Sports",                 epgNo: 464 },
  { channelNo: 106, name: "Star Sports Select 2",         hdSd: "HD", genre: "Sports",                 epgNo: 465 },
  { channelNo: 107, name: "Star Sports Select 2",         hdSd: "SD", genre: "Sports",                 epgNo: 466 },
  { channelNo: 108, name: "Sony Sports Ten 1",            hdSd: "HD", genre: "Sports",                 epgNo: 470 },
  { channelNo: 109, name: "Sony Sports Ten 1",            hdSd: "SD", genre: "Sports",                 epgNo: 471 },
  { channelNo: 110, name: "Sony Sports Ten 2",            hdSd: "HD", genre: "Sports",                 epgNo: 473 },
  { channelNo: 111, name: "Sony Sports Ten 2",            hdSd: "SD", genre: "Sports",                 epgNo: 474 },
  { channelNo: 112, name: "Sony Sports Ten 3",            hdSd: "HD", genre: "Sports",                 epgNo: 475 },
  { channelNo: 113, name: "Sony Sports Ten 3",            hdSd: "SD", genre: "Sports",                 epgNo: 476 },
  { channelNo: 114, name: "Sony Sports Ten 5",            hdSd: "HD", genre: "Sports",                 epgNo: 483 },
  { channelNo: 115, name: "Sony Sports Ten 5",            hdSd: "SD", genre: "Sports",                 epgNo: 484 },
  { channelNo: 116, name: "Sports 18 1",                  hdSd: "HD", genre: "Sports",                 epgNo: 487 },
  { channelNo: 117, name: "Sports 18 1",                  hdSd: "SD", genre: "Sports",                 epgNo: 488 },
  { channelNo: 118, name: "Sports 18 2",                  hdSd: "SD", genre: "Sports",                 epgNo: 490 },
  { channelNo: 119, name: "Sports 18 3",                  hdSd: "SD", genre: "Sports",                 epgNo: 492 },
  { channelNo: 120, name: "Eurosport",                    hdSd: "HD", genre: "Sports",                 epgNo: 495 },
  { channelNo: 121, name: "Eurosport",                    hdSd: "SD", genre: "Sports",                 epgNo: 496 },
  { channelNo: 122, name: "Star Sports First",            hdSd: "SD", genre: "Sports",                 epgNo: 497 },
  // ── Hindi News ────────────────────────────────────────────────
  { channelNo: 123, name: "DD News",                      hdSd: "HD", genre: "Hindi News",             epgNo: 501 },
  { channelNo: 124, name: "DD News",                      hdSd: "SD", genre: "Hindi News",             epgNo: 502 },
  { channelNo: 125, name: "ABP News",                     hdSd: "SD", genre: "Hindi News",             epgNo: 504 },
  { channelNo: 126, name: "NDTV India",                   hdSd: "SD", genre: "Hindi News",             epgNo: 506 },
  { channelNo: 127, name: "Aaj Tak",                      hdSd: "HD", genre: "Hindi News",             epgNo: 508 },
  { channelNo: 128, name: "Aaj Tak",                      hdSd: "SD", genre: "Hindi News",             epgNo: 509 },
  { channelNo: 129, name: "Zee News",                     hdSd: "SD", genre: "Hindi News",             epgNo: 511 },
  { channelNo: 130, name: "India TV",                     hdSd: "SD", genre: "Hindi News",             epgNo: 514 },
  { channelNo: 131, name: "News 24",                      hdSd: "SD", genre: "Hindi News",             epgNo: 516 },
  { channelNo: 132, name: "News18 India",                 hdSd: "SD", genre: "Hindi News",             epgNo: 519 },
  { channelNo: 133, name: "Zee Bharat",                   hdSd: "SD", genre: "Hindi News",             epgNo: 520 },
  { channelNo: 134, name: "R Bharat",                     hdSd: "SD", genre: "Hindi News",             epgNo: 521 },
  { channelNo: 135, name: "India News",                   hdSd: "SD", genre: "Hindi News",             epgNo: 522 },
  { channelNo: 136, name: "News Nation",                  hdSd: "SD", genre: "Hindi News",             epgNo: 523 },
  { channelNo: 137, name: "TV9 Bharatvarsh",              hdSd: "SD", genre: "Hindi News",             epgNo: 524 },
  { channelNo: 138, name: "Good News Today",              hdSd: "SD", genre: "Hindi News",             epgNo: 525 },
  { channelNo: 139, name: "Total TV",                     hdSd: "SD", genre: "Hindi News",             epgNo: 527 },
  { channelNo: 140, name: "Times Now Navbharat",          hdSd: "HD", genre: "Hindi News",             epgNo: 528 },
  { channelNo: 141, name: "Times Now Navbharat",          hdSd: "SD", genre: "Hindi News",             epgNo: 529 },
  { channelNo: 142, name: "News India 24x7",              hdSd: "SD", genre: "Hindi News",             epgNo: 530 },
  { channelNo: 143, name: "Bharat 24",                    hdSd: "SD", genre: "Hindi News",             epgNo: 531 },
  { channelNo: 144, name: "India TV Speed News",          hdSd: "HD", genre: "Hindi News",             epgNo: 532 },
  { channelNo: 145, name: "Sudarshan News",               hdSd: "SD", genre: "Hindi News",             epgNo: 534 },
  { channelNo: 146, name: "Bharat Express",               hdSd: "SD", genre: "Hindi News",             epgNo: 535 },
  { channelNo: 147, name: "India Daily 24x7",             hdSd: "SD", genre: "Hindi News",             epgNo: 536 },
  { channelNo: 148, name: "Live Times",                   hdSd: "SD", genre: "Hindi News",             epgNo: 539 },
  { channelNo: 149, name: "TV 100",                       hdSd: "SD", genre: "Hindi News",             epgNo: 540 },
  { channelNo: 150, name: "APN News",                     hdSd: "SD", genre: "Hindi News",             epgNo: 542 },
  { channelNo: 151, name: "India Voice",                  hdSd: "SD", genre: "Hindi News",             epgNo: 551 },
  { channelNo: 152, name: "News 11 Bharat",               hdSd: "SD", genre: "Hindi News",             epgNo: 552 },
  { channelNo: 153, name: "News 1 India",                 hdSd: "SD", genre: "Hindi News",             epgNo: 553 },
  { channelNo: 154, name: "Hindi Khabar",                 hdSd: "SD", genre: "Hindi News",             epgNo: 557 },
  { channelNo: 155, name: "Bharat Samachar",              hdSd: "SD", genre: "Hindi News",             epgNo: 559 },
  { channelNo: 156, name: "Khabrain Abhi Tak",            hdSd: "SD", genre: "Hindi News",             epgNo: 563 },
  { channelNo: 157, name: "Network 10",                   hdSd: "SD", genre: "Hindi News",             epgNo: 567 },
  { channelNo: 158, name: "Jantantra",                    hdSd: "SD", genre: "Hindi News",             epgNo: 568 },
  { channelNo: 159, name: "Swadesh News",                 hdSd: "SD", genre: "Hindi News",             epgNo: 573 },
  { channelNo: 160, name: "Zee Business",                 hdSd: "SD", genre: "Hindi News",             epgNo: 590 },
  { channelNo: 161, name: "CNBC Awaaz",                   hdSd: "SD", genre: "Hindi News",             epgNo: 592 },
  { channelNo: 162, name: "ET Now Swadesh",               hdSd: "SD", genre: "Hindi News",             epgNo: 594 },
  { channelNo: 163, name: "Sansad TV 1",                  hdSd: "HD", genre: "Hindi News",             epgNo: 596 },
  { channelNo: 164, name: "Sansad TV 2",                  hdSd: "HD", genre: "Hindi News",             epgNo: 597 },
  { channelNo: 165, name: "Sansad TV 1",                  hdSd: "SD", genre: "Hindi News",             epgNo: 598 },
  { channelNo: 166, name: "Sansad TV 2",                  hdSd: "SD", genre: "Hindi News",             epgNo: 599 },
  // ── English News ──────────────────────────────────────────────
  { channelNo: 167, name: "NDTV 24x7",                    hdSd: "SD", genre: "English News",           epgNo: 601 },
  { channelNo: 168, name: "Times Now World",              hdSd: "HD", genre: "English News",           epgNo: 603 },
  { channelNo: 169, name: "Times Now",                    hdSd: "SD", genre: "English News",           epgNo: 604 },
  { channelNo: 170, name: "India Today",                  hdSd: "SD", genre: "English News",           epgNo: 606 },
  { channelNo: 171, name: "CNN News18",                   hdSd: "SD", genre: "English News",           epgNo: 608 },
  { channelNo: 172, name: "NewsX",                        hdSd: "SD", genre: "English News",           epgNo: 610 },
  { channelNo: 173, name: "Mirror Now",                   hdSd: "SD", genre: "English News",           epgNo: 612 },
  { channelNo: 174, name: "WION",                         hdSd: "SD", genre: "English News",           epgNo: 613 },
  { channelNo: 175, name: "Republic TV",                  hdSd: "SD", genre: "English News",           epgNo: 616 },
  { channelNo: 176, name: "News9",                        hdSd: "SD", genre: "English News",           epgNo: 618 },
  { channelNo: 177, name: "DD India",                     hdSd: "HD", genre: "English News",           epgNo: 621 },
  { channelNo: 178, name: "DD India",                     hdSd: "SD", genre: "English News",           epgNo: 622 },
  { channelNo: 179, name: "NDTV Profit Prime",            hdSd: "SD", genre: "English News",           epgNo: 623 },
  { channelNo: 180, name: "CNBC TV18 Prime",              hdSd: "HD", genre: "English News",           epgNo: 625 },
  { channelNo: 181, name: "CNBC TV18",                    hdSd: "SD", genre: "English News",           epgNo: 626 },
  { channelNo: 182, name: "ET Now",                       hdSd: "SD", genre: "English News",           epgNo: 627 },
  { channelNo: 183, name: "Bloomberg Television",         hdSd: "SD", genre: "English News",           epgNo: 628 },
  { channelNo: 184, name: "CNN",                          hdSd: "SD", genre: "English News",           epgNo: 631 },
  { channelNo: 185, name: "BBC News",                     hdSd: "SD", genre: "English News",           epgNo: 633 },
  { channelNo: 186, name: "Al Jazeera",                   hdSd: "SD", genre: "English News",           epgNo: 637 },
  { channelNo: 187, name: "Channel News Asia",            hdSd: "SD", genre: "English News",           epgNo: 638 },
  { channelNo: 188, name: "France 24",                    hdSd: "SD", genre: "English News",           epgNo: 639 },
  { channelNo: 189, name: "TV5 Monde Asie",               hdSd: "SD", genre: "English News",           epgNo: 640 },
  { channelNo: 190, name: "DW",                           hdSd: "SD", genre: "English News",           epgNo: 641 },
  { channelNo: 191, name: "ABC Australia",                hdSd: "SD", genre: "English News",           epgNo: 642 },
  { channelNo: 192, name: "Russia Today",                 hdSd: "SD", genre: "English News",           epgNo: 643 },
  { channelNo: 193, name: "NHK WORLD-JAPAN",              hdSd: "SD", genre: "English News",           epgNo: 644 },
  // ── Kids ──────────────────────────────────────────────────────
  { channelNo: 194, name: "Hungama TV",                   hdSd: "SD", genre: "Kids",                   epgNo: 652 },
  { channelNo: 195, name: "Super Hungama",                hdSd: "SD", genre: "Kids",                   epgNo: 655 },
  { channelNo: 196, name: "Disney Channel",               hdSd: "HD", genre: "Kids",                   epgNo: 657 },
  { channelNo: 197, name: "Disney",                       hdSd: "SD", genre: "Kids",                   epgNo: 658 },
  { channelNo: 198, name: "Nick",                         hdSd: "HD", genre: "Kids",                   epgNo: 662 },
  { channelNo: 199, name: "Nick",                         hdSd: "SD", genre: "Kids",                   epgNo: 663 },
  { channelNo: 200, name: "Cartoon Network",              hdSd: "HD", genre: "Kids",                   epgNo: 666 },
  { channelNo: 201, name: "Cartoon Network",              hdSd: "SD", genre: "Kids",                   epgNo: 667 },
  { channelNo: 202, name: "Pogo",                         hdSd: "SD", genre: "Kids",                   epgNo: 670 },
  { channelNo: 203, name: "Discovery Kids",               hdSd: "SD", genre: "Kids",                   epgNo: 672 },
  { channelNo: 204, name: "Sonic",                        hdSd: "SD", genre: "Kids",                   epgNo: 674 },
  { channelNo: 205, name: "Sony Yay",                     hdSd: "SD", genre: "Kids",                   epgNo: 676 },
  { channelNo: 206, name: "Gubbare",                      hdSd: "SD", genre: "Kids",                   epgNo: 678 },
  { channelNo: 207, name: "ETV Bal Bharat",               hdSd: "HD", genre: "Kids",                   epgNo: 679 },
  { channelNo: 208, name: "ETV Bal Bharat",               hdSd: "SD", genre: "Kids",                   epgNo: 680 },
  { channelNo: 209, name: "Nick Jr",                      hdSd: "SD", genre: "Kids",                   epgNo: 685 },
  { channelNo: 210, name: "Disney Junior",                hdSd: "SD", genre: "Kids",                   epgNo: 686 },
  { channelNo: 211, name: "CBeeBies",                     hdSd: "SD", genre: "Kids",                   epgNo: 687 },
  { channelNo: 212, name: "Kushi TV",                     hdSd: "SD", genre: "Kids",                   epgNo: 692 },
  { channelNo: 213, name: "Chutti TV",                    hdSd: "SD", genre: "Kids",                   epgNo: 693 },
  { channelNo: 214, name: "Chintu TV",                    hdSd: "SD", genre: "Kids",                   epgNo: 694 },
  { channelNo: 215, name: "Kochu TV",                     hdSd: "SD", genre: "Kids",                   epgNo: 695 },
  { channelNo: 216, name: "Unique TV",                    hdSd: "SD", genre: "Kids",                   epgNo: 696 },
  // ── Knowledge & Lifestyle ─────────────────────────────────────
  { channelNo: 217, name: "National Geographic",          hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 708 },
  { channelNo: 218, name: "National Geographic",          hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 709 },
  { channelNo: 219, name: "Nat Geo Wild",                 hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 711 },
  { channelNo: 220, name: "Nat Geo Wild",                 hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 712 },
  { channelNo: 221, name: "Discovery",                    hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 713 },
  { channelNo: 222, name: "Discovery Channel",            hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 714 },
  { channelNo: 223, name: "Animal Planet",                hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 716 },
  { channelNo: 224, name: "Animal Planet",                hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 717 },
  { channelNo: 225, name: "Discovery Science",            hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 719 },
  { channelNo: 226, name: "History TV18",                 hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 720 },
  { channelNo: 227, name: "History TV18",                 hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 721 },
  { channelNo: 228, name: "Sony BBC Earth",               hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 724 },
  { channelNo: 229, name: "Sony BBC Earth",               hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 725 },
  { channelNo: 230, name: "Epic",                         hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 735 },
  { channelNo: 231, name: "Star Life",                    hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 753 },
  { channelNo: 232, name: "Star Life",                    hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 754 },
  { channelNo: 233, name: "DD Gyan Darshan",              hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 755 },
  { channelNo: 234, name: "TLC",                          hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 759 },
  { channelNo: 235, name: "TLC",                          hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 760 },
  { channelNo: 236, name: "Good Times",                   hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 762 },
  { channelNo: 237, name: "Discovery Turbo",              hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 764 },
  { channelNo: 238, name: "TravelXP",                     hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 765 },
  { channelNo: 239, name: "TravelXP",                     hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 766 },
  { channelNo: 240, name: "Food Food",                    hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 768 },
  { channelNo: 241, name: "Zee Zest",                     hdSd: "HD", genre: "Knowledge & Lifestyle",  epgNo: 769 },
  { channelNo: 242, name: "Zee Zest",                     hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 770 },
  { channelNo: 243, name: "Food XP",                      hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 771 },
  { channelNo: 244, name: "Fashion TV",                   hdSd: "SD", genre: "Knowledge & Lifestyle",  epgNo: 772 },
  // ── Music ─────────────────────────────────────────────────────
  { channelNo: 245, name: "MTV",                          hdSd: "HD", genre: "Music",                  epgNo: 806 },
  { channelNo: 246, name: "MTV",                          hdSd: "SD", genre: "Music",                  epgNo: 807 },
  { channelNo: 247, name: "9XM",                          hdSd: "SD", genre: "Music",                  epgNo: 809 },
  { channelNo: 248, name: "Zoom",                         hdSd: "SD", genre: "Music",                  epgNo: 811 },
  { channelNo: 249, name: "E24",                          hdSd: "SD", genre: "Music",                  epgNo: 813 },
  { channelNo: 250, name: "MTV Beats",                    hdSd: "HD", genre: "Music",                  epgNo: 820 },
  { channelNo: 251, name: "MTV Beats",                    hdSd: "SD", genre: "Music",                  epgNo: 821 },
  { channelNo: 252, name: "B4U Music",                    hdSd: "SD", genre: "Music",                  epgNo: 822 },
  { channelNo: 253, name: "Mastiii",                      hdSd: "SD", genre: "Music",                  epgNo: 825 },
  { channelNo: 254, name: "Zing",                         hdSd: "SD", genre: "Music",                  epgNo: 826 },
  { channelNo: 255, name: "9X Jalwa",                     hdSd: "SD", genre: "Music",                  epgNo: 830 },
  { channelNo: 256, name: "Showbox",                      hdSd: "SD", genre: "Music",                  epgNo: 835 },
  { channelNo: 257, name: "Vh1",                          hdSd: "HD", genre: "Music",                  epgNo: 855 },
  { channelNo: 258, name: "Vh1",                          hdSd: "SD", genre: "Music",                  epgNo: 856 },
  { channelNo: 259, name: "Raj Pariwar",                  hdSd: "SD", genre: "Music",                  epgNo: 857 },
  // ── Spiritual ─────────────────────────────────────────────────
  { channelNo: 260, name: "Aastha",                       hdSd: "SD", genre: "Spiritual",              epgNo: 1055 },
  { channelNo: 261, name: "Sanskar",                      hdSd: "SD", genre: "Spiritual",              epgNo: 1057 },
  { channelNo: 262, name: "Paras Gold One",               hdSd: "SD", genre: "Spiritual",              epgNo: 1059 },
  { channelNo: 263, name: "MH One Shraddha",              hdSd: "SD", genre: "Spiritual",              epgNo: 1061 },
  { channelNo: 264, name: "Sadhna TV",                    hdSd: "SD", genre: "Spiritual",              epgNo: 1063 },
  { channelNo: 265, name: "Sharnam TV",                   hdSd: "SD", genre: "Spiritual",              epgNo: 1064 },
  { channelNo: 266, name: "Peace of Mind",                hdSd: "SD", genre: "Spiritual",              epgNo: 1065 },
  { channelNo: 267, name: "Jinvani Channel",              hdSd: "SD", genre: "Spiritual",              epgNo: 1066 },
  { channelNo: 268, name: "Dharm Sandesh",                hdSd: "SD", genre: "Spiritual",              epgNo: 1067 },
  { channelNo: 269, name: "Ishwar TV",                    hdSd: "SD", genre: "Spiritual",              epgNo: 1068 },
  { channelNo: 270, name: "Satsang TV",                   hdSd: "SD", genre: "Spiritual",              epgNo: 1073 },
  { channelNo: 271, name: "Shubh TV",                     hdSd: "SD", genre: "Spiritual",              epgNo: 1074 },
  { channelNo: 272, name: "Aastha Bhajan",                hdSd: "SD", genre: "Spiritual",              epgNo: 1077 },
  { channelNo: 273, name: "Vedic",                        hdSd: "SD", genre: "Spiritual",              epgNo: 1078 },
  { channelNo: 274, name: "Subharti TV",                  hdSd: "SD", genre: "Spiritual",              epgNo: 1082 },
  { channelNo: 275, name: "Divya",                        hdSd: "SD", genre: "Spiritual",              epgNo: 1083 },
  { channelNo: 276, name: "Awakening",                    hdSd: "SD", genre: "Spiritual",              epgNo: 1084 },
  { channelNo: 277, name: "Santwani",                     hdSd: "SD", genre: "Spiritual",              epgNo: 1085 },
  { channelNo: 278, name: "Aadinath TV",                  hdSd: "SD", genre: "Spiritual",              epgNo: 1086 },
  { channelNo: 279, name: "Studio One +",                 hdSd: "SD", genre: "Spiritual",              epgNo: 1088 },
  { channelNo: 280, name: "Hare Krsna",                   hdSd: "SD", genre: "Spiritual",              epgNo: 1089 },
  // ── Hindi Regional ────────────────────────────────────────────
  { channelNo: 281, name: "MH One Dil Se",                hdSd: "SD", genre: "Hindi Regional",         epgNo: 1104 },
  { channelNo: 282, name: "Zee Biskope",                  hdSd: "SD", genre: "Hindi Regional",         epgNo: 1113 },
  { channelNo: 283, name: "Filamchi Bhojpuri",            hdSd: "SD", genre: "Hindi Regional",         epgNo: 1114 },
  { channelNo: 284, name: "Oscar Movies Bhojpuri",        hdSd: "SD", genre: "Hindi Regional",         epgNo: 1118 },
  { channelNo: 285, name: "Bhojpuri Cinema",              hdSd: "SD", genre: "Hindi Regional",         epgNo: 1119 },
  { channelNo: 286, name: "B4U Bhojpuri",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1120 },
  { channelNo: 287, name: "PASAND",                       hdSd: "SD", genre: "Hindi Regional",         epgNo: 1122 },
  { channelNo: 288, name: "Raapchik",                     hdSd: "SD", genre: "Hindi Regional",         epgNo: 1123 },
  { channelNo: 289, name: "News18 Uttar Pradesh Uttarakhand", hdSd: "SD", genre: "Hindi Regional",    epgNo: 1125 },
  { channelNo: 290, name: "Zee Uttar Pradesh Uttarakhand",hdSd: "SD", genre: "Hindi Regional",         epgNo: 1126 },
  { channelNo: 291, name: "News18 Bihar Jharkhand",       hdSd: "SD", genre: "Hindi Regional",         epgNo: 1129 },
  { channelNo: 292, name: "Zee Bihar Jharkhand",          hdSd: "SD", genre: "Hindi Regional",         epgNo: 1130 },
  { channelNo: 293, name: "India News UP UK",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1136 },
  { channelNo: 294, name: "News State UP Uttarakhand",    hdSd: "SD", genre: "Hindi Regional",         epgNo: 1137 },
  { channelNo: 295, name: "Sadhna Plus News",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1138 },
  { channelNo: 296, name: "Kashish News",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1139 },
  { channelNo: 297, name: "HNN News",                     hdSd: "SD", genre: "Hindi Regional",         epgNo: 1141 },
  { channelNo: 298, name: "Naxatra News",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1142 },
  { channelNo: 299, name: "DD Uttarakhand",               hdSd: "SD", genre: "Hindi Regional",         epgNo: 1144 },
  { channelNo: 300, name: "DD Jharkhand",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1145 },
  { channelNo: 301, name: "DD Bharati",                   hdSd: "SD", genre: "Hindi Regional",         epgNo: 1146 },
  { channelNo: 302, name: "DD Uttar Pradesh",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1147 },
  { channelNo: 303, name: "DD Bihar",                     hdSd: "SD", genre: "Hindi Regional",         epgNo: 1148 },
  { channelNo: 304, name: "News18 Madhya Pradesh Chhattisgarh", hdSd: "SD", genre: "Hindi Regional",  epgNo: 1149 },
  { channelNo: 305, name: "Zee Madhya Pradesh Chattisgarh", hdSd: "SD", genre: "Hindi Regional",      epgNo: 1150 },
  { channelNo: 306, name: "IBC 24",                       hdSd: "SD", genre: "Hindi Regional",         epgNo: 1153 },
  { channelNo: 307, name: "Bansal News",                  hdSd: "SD", genre: "Hindi Regional",         epgNo: 1154 },
  { channelNo: 308, name: "INH 24X7",                     hdSd: "SD", genre: "Hindi Regional",         epgNo: 1155 },
  { channelNo: 309, name: "India News MP CG",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1156 },
  { channelNo: 310, name: "News State MP CG",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1157 },
  { channelNo: 311, name: "Swaraj Express SMBC",          hdSd: "SD", genre: "Hindi Regional",         epgNo: 1158 },
  { channelNo: 312, name: "Sadhna News MP CG",            hdSd: "SD", genre: "Hindi Regional",         epgNo: 1159 },
  { channelNo: 313, name: "News 24 MP CG",                hdSd: "SD", genre: "Hindi Regional",         epgNo: 1160 },
  { channelNo: 314, name: "Anaadi TV",                    hdSd: "SD", genre: "Hindi Regional",         epgNo: 1161 },
  { channelNo: 315, name: "TV27 News",                    hdSd: "SD", genre: "Hindi Regional",         epgNo: 1163 },
  { channelNo: 316, name: "Asian News",                   hdSd: "SD", genre: "Hindi Regional",         epgNo: 1165 },
  { channelNo: 317, name: "TV24",                         hdSd: "SD", genre: "Hindi Regional",         epgNo: 1166 },
  { channelNo: 318, name: "NDTV MPCG",                    hdSd: "SD", genre: "Hindi Regional",         epgNo: 1167 },
  { channelNo: 319, name: "Vistaar News",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1168 },
  { channelNo: 320, name: "DA News Plus",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1169 },
  { channelNo: 321, name: "BS TV",                        hdSd: "SD", genre: "Hindi Regional",         epgNo: 1170 },
  { channelNo: 322, name: "Sadhna Prime News",            hdSd: "SD", genre: "Hindi Regional",         epgNo: 1171 },
  { channelNo: 323, name: "DD Chhattisgarh",              hdSd: "SD", genre: "Hindi Regional",         epgNo: 1174 },
  { channelNo: 324, name: "DD Madhya Pradesh",            hdSd: "SD", genre: "Hindi Regional",         epgNo: 1175 },
  { channelNo: 325, name: "News18 Rajasthan",             hdSd: "SD", genre: "Hindi Regional",         epgNo: 1176 },
  { channelNo: 326, name: "Zee Rajasthan News",           hdSd: "SD", genre: "Hindi Regional",         epgNo: 1177 },
  { channelNo: 327, name: "First India Rajasthan",        hdSd: "SD", genre: "Hindi Regional",         epgNo: 1182 },
  { channelNo: 328, name: "India News Rajasthan",         hdSd: "SD", genre: "Hindi Regional",         epgNo: 1183 },
  { channelNo: 329, name: "Jan TV",                       hdSd: "SD", genre: "Hindi Regional",         epgNo: 1185 },
  { channelNo: 330, name: "Sach Bedhadak",                hdSd: "SD", genre: "Hindi Regional",         epgNo: 1186 },
  { channelNo: 331, name: "NDTV Rajasthan",               hdSd: "SD", genre: "Hindi Regional",         epgNo: 1188 },
  { channelNo: 332, name: "DD Rajasthan",                 hdSd: "SD", genre: "Hindi Regional",         epgNo: 1190 },
  { channelNo: 333, name: "News18 Jammu Kashmir Ladakh Himachal Haryana", hdSd: "SD", genre: "Hindi Regional", epgNo: 1191 },
  { channelNo: 334, name: "Salaam TV",                    hdSd: "SD", genre: "Hindi Regional",         epgNo: 1192 },
  { channelNo: 335, name: "Channel Win",                  hdSd: "SD", genre: "Hindi Regional",         epgNo: 1193 },
  { channelNo: 336, name: "Gulistan News",                hdSd: "SD", genre: "Hindi Regional",         epgNo: 1194 },
  { channelNo: 337, name: "DD Urdu",                      hdSd: "SD", genre: "Hindi Regional",         epgNo: 1199 },
  // ── Marathi Regional ─────────────────────────────────────────
  { channelNo: 338, name: "Colors Marathi",               hdSd: "HD", genre: "Marathi Regional",       epgNo: 1201 },
  { channelNo: 339, name: "Colors Marathi",               hdSd: "SD", genre: "Marathi Regional",       epgNo: 1202 },
  { channelNo: 340, name: "Zee Marathi",                  hdSd: "HD", genre: "Marathi Regional",       epgNo: 1203 },
  { channelNo: 341, name: "Zee Marathi",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1204 },
  { channelNo: 342, name: "Star Pravah",                  hdSd: "HD", genre: "Marathi Regional",       epgNo: 1207 },
  { channelNo: 343, name: "Star Pravah",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1208 },
  { channelNo: 344, name: "Zee Yuva",                     hdSd: "SD", genre: "Marathi Regional",       epgNo: 1211 },
  { channelNo: 345, name: "Sony Marathi",                 hdSd: "SD", genre: "Marathi Regional",       epgNo: 1213 },
  { channelNo: 346, name: "Sun Marathi",                  hdSd: "HD", genre: "Marathi Regional",       epgNo: 1216 },
  { channelNo: 347, name: "Sun Marathi",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1217 },
  { channelNo: 348, name: "Zee Talkies",                  hdSd: "HD", genre: "Marathi Regional",       epgNo: 1225 },
  { channelNo: 349, name: "Zee Talkies",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1226 },
  { channelNo: 350, name: "Star Pravah Pictures",         hdSd: "HD", genre: "Marathi Regional",       epgNo: 1227 },
  { channelNo: 351, name: "Pravah Pictures",              hdSd: "SD", genre: "Marathi Regional",       epgNo: 1228 },
  { channelNo: 352, name: "Fakt Marathi",                 hdSd: "SD", genre: "Marathi Regional",       epgNo: 1229 },
  { channelNo: 353, name: "Shemaroo Marathi Bana",        hdSd: "SD", genre: "Marathi Regional",       epgNo: 1230 },
  { channelNo: 354, name: "ABP Majha",                    hdSd: "SD", genre: "Marathi Regional",       epgNo: 1255 },
  { channelNo: 355, name: "News18 Lokmat",                hdSd: "SD", genre: "Marathi Regional",       epgNo: 1257 },
  { channelNo: 356, name: "Zee 24 Taas",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1259 },
  { channelNo: 357, name: "Saam TV",                      hdSd: "SD", genre: "Marathi Regional",       epgNo: 1261 },
  { channelNo: 358, name: "Jai Maharashtra",              hdSd: "SD", genre: "Marathi Regional",       epgNo: 1262 },
  { channelNo: 359, name: "TV9 Marathi",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1263 },
  { channelNo: 360, name: "Lokshahi Marathi",             hdSd: "SD", genre: "Marathi Regional",       epgNo: 1265 },
  { channelNo: 361, name: "Pudhari News",                 hdSd: "SD", genre: "Marathi Regional",       epgNo: 1267 },
  { channelNo: 362, name: "NDTV Marathi",                 hdSd: "SD", genre: "Marathi Regional",       epgNo: 1268 },
  { channelNo: 363, name: "DD Sahyadri",                  hdSd: "SD", genre: "Marathi Regional",       epgNo: 1274 },
  { channelNo: 364, name: "Sangeet Marathi",              hdSd: "SD", genre: "Marathi Regional",       epgNo: 1277 },
  // ── Bengali Regional ──────────────────────────────────────────
  { channelNo: 365, name: "Colors Bangla",                hdSd: "HD", genre: "Bengali Regional",       epgNo: 1302 },
  { channelNo: 366, name: "Colors Bangla",                hdSd: "SD", genre: "Bengali Regional",       epgNo: 1303 },
  { channelNo: 367, name: "Zee Bangla",                   hdSd: "HD", genre: "Bengali Regional",       epgNo: 1306 },
  { channelNo: 368, name: "Zee Bangla",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1307 },
  { channelNo: 369, name: "Star Jalsha",                  hdSd: "HD", genre: "Bengali Regional",       epgNo: 1309 },
  { channelNo: 370, name: "Star Jalsha",                  hdSd: "SD", genre: "Bengali Regional",       epgNo: 1310 },
  { channelNo: 371, name: "Sony Aath",                    hdSd: "SD", genre: "Bengali Regional",       epgNo: 1312 },
  { channelNo: 372, name: "Sun Bangla",                   hdSd: "HD", genre: "Bengali Regional",       epgNo: 1316 },
  { channelNo: 373, name: "Sun Bangla",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1317 },
  { channelNo: 374, name: "Aakaash Aath",                 hdSd: "SD", genre: "Bengali Regional",       epgNo: 1320 },
  { channelNo: 375, name: "Ruposhi Bangla",               hdSd: "SD", genre: "Bengali Regional",       epgNo: 1321 },
  { channelNo: 376, name: "Enterr10 Bangla",              hdSd: "SD", genre: "Bengali Regional",       epgNo: 1322 },
  { channelNo: 377, name: "Jalsha Movies",                hdSd: "HD", genre: "Bengali Regional",       epgNo: 1326 },
  { channelNo: 378, name: "Jalsha Movies",                hdSd: "SD", genre: "Bengali Regional",       epgNo: 1327 },
  { channelNo: 379, name: "Zee Bangla Cinema",            hdSd: "SD", genre: "Bengali Regional",       epgNo: 1329 },
  { channelNo: 380, name: "Colors Bangla Cinema",         hdSd: "SD", genre: "Bengali Regional",       epgNo: 1331 },
  { channelNo: 381, name: "Khushboo Bangla",              hdSd: "SD", genre: "Bengali Regional",       epgNo: 1341 },
  { channelNo: 382, name: "Rongeen TV",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1355 },
  { channelNo: 383, name: "ABP Ananda",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1360 },
  { channelNo: 384, name: "Zee 24 Ghanta",                hdSd: "SD", genre: "Bengali Regional",       epgNo: 1362 },
  { channelNo: 385, name: "Kolkata TV",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1363 },
  { channelNo: 386, name: "News18 Bangla",                hdSd: "SD", genre: "Bengali Regional",       epgNo: 1365 },
  { channelNo: 387, name: "TV9 Bangla",                   hdSd: "SD", genre: "Bengali Regional",       epgNo: 1366 },
  { channelNo: 388, name: "Republic Bangla",              hdSd: "SD", genre: "Bengali Regional",       epgNo: 1367 },
  { channelNo: 389, name: "News Time Bangla",             hdSd: "SD", genre: "Bengali Regional",       epgNo: 1368 },
  { channelNo: 390, name: "CTVN AKD Plus",               hdSd: "SD", genre: "Bengali Regional",       epgNo: 1369 },
  { channelNo: 391, name: "Calcutta News",                hdSd: "SD", genre: "Bengali Regional",       epgNo: 1370 },
  { channelNo: 392, name: "DD Bangla",                    hdSd: "SD", genre: "Bengali Regional",       epgNo: 1379 },
  { channelNo: 393, name: "Sangeet Bangla",               hdSd: "SD", genre: "Bengali Regional",       epgNo: 1380 },
  // ── Telugu Regional ───────────────────────────────────────────
  { channelNo: 394, name: "Zee Telugu",                   hdSd: "HD", genre: "Telugu Regional",        epgNo: 1403 },
  { channelNo: 395, name: "Zee Telugu",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1404 },
  { channelNo: 396, name: "Gemini TV",                    hdSd: "HD", genre: "Telugu Regional",        epgNo: 1405 },
  { channelNo: 397, name: "Gemini TV",                    hdSd: "SD", genre: "Telugu Regional",        epgNo: 1406 },
  { channelNo: 398, name: "Star Maa",                     hdSd: "HD", genre: "Telugu Regional",        epgNo: 1408 },
  { channelNo: 399, name: "Star Maa",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1409 },
  { channelNo: 400, name: "ETV",                          hdSd: "HD", genre: "Telugu Regional",        epgNo: 1411 },
  { channelNo: 401, name: "ETV Telugu",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1412 },
  { channelNo: 402, name: "Gemini Life",                  hdSd: "SD", genre: "Telugu Regional",        epgNo: 1415 },
  { channelNo: 403, name: "ETV Plus",                     hdSd: "HD", genre: "Telugu Regional",        epgNo: 1416 },
  { channelNo: 404, name: "ETV Plus",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1417 },
  { channelNo: 405, name: "Telugu Naaptol",               hdSd: "SD", genre: "Telugu Regional",        epgNo: 1419 },
  { channelNo: 406, name: "Vissa TV",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1422 },
  { channelNo: 407, name: "Vanitha",                      hdSd: "SD", genre: "Telugu Regional",        epgNo: 1425 },
  { channelNo: 408, name: "Mahaa Max",                    hdSd: "SD", genre: "Telugu Regional",        epgNo: 1426 },
  { channelNo: 409, name: "Gemini Movies",                hdSd: "HD", genre: "Telugu Regional",        epgNo: 1430 },
  { channelNo: 410, name: "Gemini Movies",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1431 },
  { channelNo: 411, name: "Star Maa Movies",              hdSd: "HD", genre: "Telugu Regional",        epgNo: 1432 },
  { channelNo: 412, name: "Star Maa Movies",              hdSd: "SD", genre: "Telugu Regional",        epgNo: 1433 },
  { channelNo: 413, name: "Star Maa Gold",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1435 },
  { channelNo: 414, name: "Zee Cinemalu",                 hdSd: "HD", genre: "Telugu Regional",        epgNo: 1437 },
  { channelNo: 415, name: "Zee Cinemalu",                 hdSd: "SD", genre: "Telugu Regional",        epgNo: 1438 },
  { channelNo: 416, name: "ETV Cinema",                   hdSd: "HD", genre: "Telugu Regional",        epgNo: 1439 },
  { channelNo: 417, name: "ETV Cinema",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1440 },
  { channelNo: 418, name: "Gemini Comedy",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1442 },
  { channelNo: 419, name: "Star Sports 1 Telugu",         hdSd: "HD", genre: "Telugu Regional",        epgNo: 1445 },
  { channelNo: 420, name: "Star Sports 1 Telugu",         hdSd: "SD", genre: "Telugu Regional",        epgNo: 1446 },
  { channelNo: 421, name: "ETV Life",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1451 },
  { channelNo: 422, name: "ETV Abhiruchi",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1453 },
  { channelNo: 423, name: "Sakshi TV",                    hdSd: "SD", genre: "Telugu Regional",        epgNo: 1456 },
  { channelNo: 424, name: "ETV Andhra Pradesh",           hdSd: "SD", genre: "Telugu Regional",        epgNo: 1457 },
  { channelNo: 425, name: "TV5 News",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1458 },
  { channelNo: 426, name: "TV9 Telugu",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1459 },
  { channelNo: 427, name: "NTV Telugu",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1460 },
  { channelNo: 428, name: "ABN Andhra Jyothy",            hdSd: "SD", genre: "Telugu Regional",        epgNo: 1461 },
  { channelNo: 429, name: "T News",                       hdSd: "SD", genre: "Telugu Regional",        epgNo: 1462 },
  { channelNo: 430, name: "V6 News",                      hdSd: "SD", genre: "Telugu Regional",        epgNo: 1463 },
  { channelNo: 431, name: "ETV Telangana",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1464 },
  { channelNo: 432, name: "HM TV",                        hdSd: "SD", genre: "Telugu Regional",        epgNo: 1465 },
  { channelNo: 433, name: "Raj News Telugu",              hdSd: "SD", genre: "Telugu Regional",        epgNo: 1466 },
  { channelNo: 434, name: "10 TV",                        hdSd: "SD", genre: "Telugu Regional",        epgNo: 1467 },
  { channelNo: 435, name: "Swatantra TV",                 hdSd: "SD", genre: "Telugu Regional",        epgNo: 1468 },
  { channelNo: 436, name: "4TV News",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1470 },
  { channelNo: 437, name: "Prime9 Plus",                  hdSd: "SD", genre: "Telugu Regional",        epgNo: 1471 },
  { channelNo: 438, name: "Big TV",                       hdSd: "SD", genre: "Telugu Regional",        epgNo: 1472 },
  { channelNo: 439, name: "Mahaa News",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1474 },
  { channelNo: 440, name: "BRK News",                     hdSd: "SD", genre: "Telugu Regional",        epgNo: 1475 },
  { channelNo: 441, name: "6TV",                          hdSd: "SD", genre: "Telugu Regional",        epgNo: 1476 },
  { channelNo: 442, name: "Zee Telugu News",              hdSd: "SD", genre: "Telugu Regional",        epgNo: 1477 },
  { channelNo: 443, name: "DD Saptagiri",                 hdSd: "SD", genre: "Telugu Regional",        epgNo: 1481 },
  { channelNo: 444, name: "DD Yadagiri",                  hdSd: "SD", genre: "Telugu Regional",        epgNo: 1482 },
  { channelNo: 445, name: "Gemini Music",                 hdSd: "HD", genre: "Telugu Regional",        epgNo: 1483 },
  { channelNo: 446, name: "Gemini Music",                 hdSd: "SD", genre: "Telugu Regional",        epgNo: 1484 },
  { channelNo: 447, name: "Star Maa Music",               hdSd: "SD", genre: "Telugu Regional",        epgNo: 1486 },
  { channelNo: 448, name: "Raj Musix Telugu",             hdSd: "SD", genre: "Telugu Regional",        epgNo: 1487 },
  { channelNo: 449, name: "Bhakti TV",                    hdSd: "SD", genre: "Telugu Regional",        epgNo: 1490 },
  { channelNo: 450, name: "Subhavaartha TV",              hdSd: "SD", genre: "Telugu Regional",        epgNo: 1491 },
  { channelNo: 451, name: "Aradana TV",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1492 },
  { channelNo: 452, name: "Swara Sagar",                  hdSd: "SD", genre: "Telugu Regional",        epgNo: 1493 },
  { channelNo: 453, name: "Hindu Dharmam",                hdSd: "SD", genre: "Telugu Regional",        epgNo: 1494 },
  { channelNo: 454, name: "Calvary TV",                   hdSd: "SD", genre: "Telugu Regional",        epgNo: 1495 },
  { channelNo: 455, name: "Nireekshana TV",               hdSd: "SD", genre: "Telugu Regional",        epgNo: 1496 },
  { channelNo: 456, name: "SVBC",                         hdSd: "SD", genre: "Telugu Regional",        epgNo: 1499 },
  // ── Tamil Regional ────────────────────────────────────────────
  { channelNo: 457, name: "Sun TV",                       hdSd: "HD", genre: "Tamil Regional",         epgNo: 1503 },
  { channelNo: 458, name: "Sun TV",                       hdSd: "SD", genre: "Tamil Regional",         epgNo: 1504 },
  { channelNo: 459, name: "Sun Life",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1506 },
  { channelNo: 460, name: "Star Vijay",                   hdSd: "HD", genre: "Tamil Regional",         epgNo: 1507 },
  { channelNo: 461, name: "Star Vijay",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1508 },
  { channelNo: 462, name: "Zee Tamil",                    hdSd: "HD", genre: "Tamil Regional",         epgNo: 1510 },
  { channelNo: 463, name: "Zee Tamil",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1511 },
  { channelNo: 464, name: "Vijay Super",                  hdSd: "HD", genre: "Tamil Regional",         epgNo: 1512 },
  { channelNo: 465, name: "Vijay Super",                  hdSd: "SD", genre: "Tamil Regional",         epgNo: 1513 },
  { channelNo: 466, name: "Colors Tamil",                 hdSd: "HD", genre: "Tamil Regional",         epgNo: 1514 },
  { channelNo: 467, name: "Colors Tamil",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1515 },
  { channelNo: 468, name: "Jaya TV",                      hdSd: "HD", genre: "Tamil Regional",         epgNo: 1517 },
  { channelNo: 469, name: "Kalaignar TV",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1518 },
  { channelNo: 470, name: "Raj TV",                       hdSd: "SD", genre: "Tamil Regional",         epgNo: 1520 },
  { channelNo: 471, name: "D Tamil",                      hdSd: "SD", genre: "Tamil Regional",         epgNo: 1521 },
  { channelNo: 472, name: "Raj Digital Plus",             hdSd: "SD", genre: "Tamil Regional",         epgNo: 1522 },
  { channelNo: 473, name: "Mega TV",                      hdSd: "SD", genre: "Tamil Regional",         epgNo: 1523 },
  { channelNo: 474, name: "Mega 24",                      hdSd: "SD", genre: "Tamil Regional",         epgNo: 1524 },
  { channelNo: 475, name: "Tamil Naaptol",                hdSd: "SD", genre: "Tamil Regional",         epgNo: 1525 },
  { channelNo: 476, name: "Vasanth TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1530 },
  { channelNo: 477, name: "Sirippoli",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1531 },
  { channelNo: 478, name: "Polimer TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1532 },
  { channelNo: 479, name: "Makkal TV",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1533 },
  { channelNo: 480, name: "Peppers TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1534 },
  { channelNo: 481, name: "Vendhar TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1536 },
  { channelNo: 482, name: "Thanthi One",                  hdSd: "SD", genre: "Tamil Regional",         epgNo: 1537 },
  { channelNo: 483, name: "KTV",                          hdSd: "HD", genre: "Tamil Regional",         epgNo: 1540 },
  { channelNo: 484, name: "KTV",                          hdSd: "SD", genre: "Tamil Regional",         epgNo: 1541 },
  { channelNo: 485, name: "Adithya TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1543 },
  { channelNo: 486, name: "J Movies",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1544 },
  { channelNo: 487, name: "Zee Thirai",                   hdSd: "HD", genre: "Tamil Regional",         epgNo: 1545 },
  { channelNo: 488, name: "Zee Thirai",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1546 },
  { channelNo: 489, name: "Star Sports 1 Tamil",          hdSd: "HD", genre: "Tamil Regional",         epgNo: 1550 },
  { channelNo: 490, name: "Star Sports 1 Tamil",          hdSd: "SD", genre: "Tamil Regional",         epgNo: 1551 },
  { channelNo: 491, name: "Sony Sports Ten 4",            hdSd: "SD", genre: "Tamil Regional",         epgNo: 1552 },
  { channelNo: 492, name: "TravelXP Tamil",               hdSd: "SD", genre: "Tamil Regional",         epgNo: 1553 },
  { channelNo: 493, name: "Sony Sports Ten 4",            hdSd: "HD", genre: "Tamil Regional",         epgNo: 1554 },
  { channelNo: 494, name: "Puthiya Thalaimurai",          hdSd: "SD", genre: "Tamil Regional",         epgNo: 1556 },
  { channelNo: 495, name: "Thanthi TV",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1557 },
  { channelNo: 496, name: "Jaya Plus",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1558 },
  { channelNo: 497, name: "Sun News",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1559 },
  { channelNo: 498, name: "Polimer News",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1561 },
  { channelNo: 499, name: "News18 Tamil Nadu",            hdSd: "SD", genre: "Tamil Regional",         epgNo: 1562 },
  { channelNo: 500, name: "Seithigal TV",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1563 },
  { channelNo: 501, name: "Raj News Tamil",               hdSd: "SD", genre: "Tamil Regional",         epgNo: 1564 },
  { channelNo: 502, name: "Sathiyam TV",                  hdSd: "SD", genre: "Tamil Regional",         epgNo: 1565 },
  { channelNo: 503, name: "Malaimurasu Seithigal",        hdSd: "SD", genre: "Tamil Regional",         epgNo: 1566 },
  { channelNo: 504, name: "News J",                       hdSd: "SD", genre: "Tamil Regional",         epgNo: 1568 },
  { channelNo: 505, name: "News Tamil 24x7",              hdSd: "SD", genre: "Tamil Regional",         epgNo: 1569 },
  { channelNo: 506, name: "Tamil Janam",                  hdSd: "SD", genre: "Tamil Regional",         epgNo: 1570 },
  { channelNo: 507, name: "DD Tamil",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1578 },
  { channelNo: 508, name: "Sun Music",                    hdSd: "HD", genre: "Tamil Regional",         epgNo: 1579 },
  { channelNo: 509, name: "Sun Music",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1580 },
  { channelNo: 510, name: "Jaya Max",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1581 },
  { channelNo: 511, name: "Raj Musix",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1582 },
  { channelNo: 512, name: "Vijay Takkar",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1583 },
  { channelNo: 513, name: "Isaiaruvi",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1584 },
  { channelNo: 514, name: "Murasu TV",                    hdSd: "SD", genre: "Tamil Regional",         epgNo: 1585 },
  { channelNo: 515, name: "Mega Musiq",                   hdSd: "SD", genre: "Tamil Regional",         epgNo: 1586 },
  { channelNo: 516, name: "Jothi TV",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1587 },
  { channelNo: 517, name: "Raj Nagaichuvai",              hdSd: "SD", genre: "Tamil Regional",         epgNo: 1588 },
  { channelNo: 518, name: "Madha TV",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1590 },
  { channelNo: 519, name: "Angel TV",                     hdSd: "SD", genre: "Tamil Regional",         epgNo: 1591 },
  { channelNo: 520, name: "Nambikkai TV",                 hdSd: "SD", genre: "Tamil Regional",         epgNo: 1592 },
  { channelNo: 521, name: "SVBC 2",                       hdSd: "SD", genre: "Tamil Regional",         epgNo: 1599 },
  // ── Kannada Regional ──────────────────────────────────────────
  { channelNo: 522, name: "Udaya TV",                     hdSd: "HD", genre: "Kannada Regional",       epgNo: 1603 },
  { channelNo: 523, name: "Udaya TV",                     hdSd: "SD", genre: "Kannada Regional",       epgNo: 1604 },
  { channelNo: 524, name: "Colors Kannada",               hdSd: "HD", genre: "Kannada Regional",       epgNo: 1605 },
  { channelNo: 525, name: "Colors Kannada",               hdSd: "SD", genre: "Kannada Regional",       epgNo: 1606 },
  { channelNo: 526, name: "Star Suvarna",                 hdSd: "HD", genre: "Kannada Regional",       epgNo: 1609 },
  { channelNo: 527, name: "Star Suvarna",                 hdSd: "SD", genre: "Kannada Regional",       epgNo: 1610 },
  { channelNo: 528, name: "Zee Kannada",                  hdSd: "HD", genre: "Kannada Regional",       epgNo: 1611 },
  { channelNo: 529, name: "Zee Kannada",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1612 },
  { channelNo: 530, name: "Colors Super",                 hdSd: "SD", genre: "Kannada Regional",       epgNo: 1615 },
  { channelNo: 531, name: "Kannada Naaptol",              hdSd: "SD", genre: "Kannada Regional",       epgNo: 1617 },
  { channelNo: 532, name: "Sirikannada All Time",         hdSd: "SD", genre: "Kannada Regional",       epgNo: 1618 },
  { channelNo: 533, name: "Udaya Movies",                 hdSd: "SD", genre: "Kannada Regional",       epgNo: 1626 },
  { channelNo: 534, name: "Udaya Comedy",                 hdSd: "SD", genre: "Kannada Regional",       epgNo: 1628 },
  { channelNo: 535, name: "Star Suvarna Plus",            hdSd: "SD", genre: "Kannada Regional",       epgNo: 1630 },
  { channelNo: 536, name: "Colors Kannada Cinema",        hdSd: "SD", genre: "Kannada Regional",       epgNo: 1632 },
  { channelNo: 537, name: "Zee Picchar",                  hdSd: "HD", genre: "Kannada Regional",       epgNo: 1633 },
  { channelNo: 538, name: "Zee Picchar",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1634 },
  { channelNo: 539, name: "Public Movies",                hdSd: "SD", genre: "Kannada Regional",       epgNo: 1639 },
  { channelNo: 540, name: "Star Sports 1 Kannada",        hdSd: "SD", genre: "Kannada Regional",       epgNo: 1645 },
  { channelNo: 541, name: "TV9 Kannada",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1653 },
  { channelNo: 542, name: "News18 Kannada",               hdSd: "SD", genre: "Kannada Regional",       epgNo: 1654 },
  { channelNo: 543, name: "Public TV",                    hdSd: "SD", genre: "Kannada Regional",       epgNo: 1655 },
  { channelNo: 544, name: "Asianet Suvarna News",         hdSd: "SD", genre: "Kannada Regional",       epgNo: 1656 },
  { channelNo: 545, name: "TV5 Kannada",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1657 },
  { channelNo: 546, name: "Raj News Kannada",             hdSd: "SD", genre: "Kannada Regional",       epgNo: 1658 },
  { channelNo: 547, name: "R Kannada",                    hdSd: "SD", genre: "Kannada Regional",       epgNo: 1659 },
  { channelNo: 548, name: "Power TV",                     hdSd: "SD", genre: "Kannada Regional",       epgNo: 1660 },
  { channelNo: 549, name: "News 1st Kannada",             hdSd: "SD", genre: "Kannada Regional",       epgNo: 1661 },
  { channelNo: 550, name: "Zee Kannada News",             hdSd: "SD", genre: "Kannada Regional",       epgNo: 1664 },
  { channelNo: 551, name: "DD Chandana",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1672 },
  { channelNo: 552, name: "Udaya Music",                  hdSd: "SD", genre: "Kannada Regional",       epgNo: 1673 },
  { channelNo: 553, name: "Raj Musix Kannada",            hdSd: "SD", genre: "Kannada Regional",       epgNo: 1674 },
  { channelNo: 554, name: "Public Music",                 hdSd: "SD", genre: "Kannada Regional",       epgNo: 1677 },
  { channelNo: 555, name: "Sri Sankara TV",               hdSd: "SD", genre: "Kannada Regional",       epgNo: 1685 },
  { channelNo: 556, name: "Ayush TV",                     hdSd: "SD", genre: "Kannada Regional",       epgNo: 1686 },
  { channelNo: 557, name: "SVBC 3",                       hdSd: "SD", genre: "Kannada Regional",       epgNo: 1698 },
  // ── Gujarati Regional ─────────────────────────────────────────
  { channelNo: 558, name: "Colors Gujarati",              hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1702 },
  { channelNo: 559, name: "Colors Gujarati Cinema",       hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1711 },
  { channelNo: 560, name: "TV9 Gujarati",                 hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1720 },
  { channelNo: 561, name: "Gujarat Samachar TV",          hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1721 },
  { channelNo: 562, name: "Sandesh News",                 hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1722 },
  { channelNo: 563, name: "CNBC Bajaar",                  hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1724 },
  { channelNo: 564, name: "News18 Gujarati",              hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1726 },
  { channelNo: 565, name: "ABP Asmita",                   hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1728 },
  { channelNo: 566, name: "VTV News",                     hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1729 },
  { channelNo: 567, name: "Zee 24 Kalak",                 hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1731 },
  { channelNo: 568, name: "India News Gujarat",           hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1732 },
  { channelNo: 569, name: "Gujarat First",                hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1735 },
  { channelNo: 570, name: "News Capital",                 hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1737 },
  { channelNo: 571, name: "DD Girnar",                    hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1739 },
  { channelNo: 572, name: "Aastha Gujarati",              hdSd: "SD", genre: "Gujarati Regional",      epgNo: 1743 },
  // ── Odia Regional ─────────────────────────────────────────────
  { channelNo: 573, name: "Colors Odia",                  hdSd: "SD", genre: "Odia Regional",          epgNo: 1752 },
  { channelNo: 574, name: "Tarang TV",                    hdSd: "SD", genre: "Odia Regional",          epgNo: 1754 },
  { channelNo: 575, name: "Zee Sarthak",                  hdSd: "SD", genre: "Odia Regional",          epgNo: 1756 },
  { channelNo: 576, name: "Sidharth TV",                  hdSd: "SD", genre: "Odia Regional",          epgNo: 1757 },
  { channelNo: 577, name: "Star Kiran",                   hdSd: "HD", genre: "Odia Regional",          epgNo: 1758 },
  { channelNo: 578, name: "Star Kiran",                   hdSd: "SD", genre: "Odia Regional",          epgNo: 1759 },
  { channelNo: 579, name: "Alankar",                      hdSd: "SD", genre: "Odia Regional",          epgNo: 1763 },
  { channelNo: 580, name: "Sidharth Gold",                hdSd: "SD", genre: "Odia Regional",          epgNo: 1766 },
  { channelNo: 581, name: "OTV",                          hdSd: "SD", genre: "Odia Regional",          epgNo: 1771 },
  { channelNo: 582, name: "Kanak News",                   hdSd: "SD", genre: "Odia Regional",          epgNo: 1774 },
  { channelNo: 583, name: "News18 Odia",                  hdSd: "SD", genre: "Odia Regional",          epgNo: 1776 },
  { channelNo: 584, name: "Kalinga TV",                   hdSd: "SD", genre: "Odia Regional",          epgNo: 1777 },
  { channelNo: 585, name: "Prameya News 7",               hdSd: "SD", genre: "Odia Regional",          epgNo: 1778 },
  { channelNo: 586, name: "Nandighosha TV",               hdSd: "SD", genre: "Odia Regional",          epgNo: 1779 },
  { channelNo: 587, name: "Argus News",                   hdSd: "SD", genre: "Odia Regional",          epgNo: 1780 },
  { channelNo: 588, name: "DD Odia",                      hdSd: "SD", genre: "Odia Regional",          epgNo: 1785 },
  { channelNo: 589, name: "Tarang Music",                 hdSd: "SD", genre: "Odia Regional",          epgNo: 1786 },
  { channelNo: 590, name: "Prarthana Life",               hdSd: "SD", genre: "Odia Regional",          epgNo: 1795 },
  { channelNo: 591, name: "Sidharth Utsav",               hdSd: "SD", genre: "Odia Regional",          epgNo: 1796 },
  { channelNo: 592, name: "Jay Jagannath",                hdSd: "SD", genre: "Odia Regional",          epgNo: 1799 },
  // ── Malayalam Regional ────────────────────────────────────────
  { channelNo: 593, name: "Surya TV",                     hdSd: "HD", genre: "Malayalam Regional",     epgNo: 1802 },
  { channelNo: 594, name: "Surya TV",                     hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1803 },
  { channelNo: 595, name: "Asianet",                      hdSd: "HD", genre: "Malayalam Regional",     epgNo: 1806 },
  { channelNo: 596, name: "Asianet",                      hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1807 },
  { channelNo: 597, name: "Asianet Plus",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1809 },
  { channelNo: 598, name: "Zee Keralam",                  hdSd: "HD", genre: "Malayalam Regional",     epgNo: 1811 },
  { channelNo: 599, name: "Zee Keralam",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1812 },
  { channelNo: 600, name: "Flowers",                      hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1814 },
  { channelNo: 601, name: "Mazhavil Manorama",            hdSd: "HD", genre: "Malayalam Regional",     epgNo: 1818 },
  { channelNo: 602, name: "Mazhavil Manorama",            hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1819 },
  { channelNo: 603, name: "Kairali TV",                   hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1820 },
  { channelNo: 604, name: "We TV",                        hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1822 },
  { channelNo: 605, name: "Amrita TV",                    hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1823 },
  { channelNo: 606, name: "Surya Movies",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1826 },
  { channelNo: 607, name: "Asianet Movies",               hdSd: "HD", genre: "Malayalam Regional",     epgNo: 1827 },
  { channelNo: 608, name: "Asianet Movies",               hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1828 },
  { channelNo: 609, name: "Surya Comedy",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1830 },
  { channelNo: 610, name: "Safari TV",                    hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1838 },
  { channelNo: 611, name: "Asianet News",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1841 },
  { channelNo: 612, name: "News18 Kerala",                hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1842 },
  { channelNo: 613, name: "Manorama News",                hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1843 },
  { channelNo: 614, name: "Mathrubhumi News",             hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1844 },
  { channelNo: 615, name: "Kairali News",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1846 },
  { channelNo: 616, name: "Jai Hind TV",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1847 },
  { channelNo: 617, name: "Jeevan TV",                    hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1848 },
  { channelNo: 618, name: "Media One TV",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1849 },
  { channelNo: 619, name: "Janam TV",                     hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1850 },
  { channelNo: 620, name: "Kaumudy",                      hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1851 },
  { channelNo: 621, name: "Raj News Malayalam",           hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1853 },
  { channelNo: 622, name: "Twenty four",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1854 },
  { channelNo: 623, name: "Reporter TV",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1855 },
  { channelNo: 624, name: "Shekinah",                     hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1856 },
  { channelNo: 625, name: "News Malayalam 24x7",          hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1857 },
  { channelNo: 626, name: "DD Malayalam",                 hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1874 },
  { channelNo: 627, name: "Surya Music",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1875 },
  { channelNo: 628, name: "Raj Musix Malayalam",          hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1877 },
  { channelNo: 629, name: "Kappa TV",                     hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1878 },
  { channelNo: 630, name: "Goodness",                     hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1885 },
  { channelNo: 631, name: "God TV",                       hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1886 },
  { channelNo: 632, name: "SHALOM TV",                    hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1887 },
  { channelNo: 633, name: "Harvest TV 24x7",              hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1888 },
  { channelNo: 634, name: "Powervision",                  hdSd: "SD", genre: "Malayalam Regional",     epgNo: 1899 },
  // ── Punjabi Regional ──────────────────────────────────────────
  { channelNo: 635, name: "Zee Punjabi",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1903 },
  { channelNo: 636, name: "PTC Punjabi",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1906 },
  { channelNo: 637, name: "MH One",                       hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1907 },
  { channelNo: 638, name: "Pitaara Movies",               hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1911 },
  { channelNo: 639, name: "PTC Punjabi Gold",             hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1912 },
  { channelNo: 640, name: "Zee Punjab Haryana Himachal Pradesh", hdSd: "SD", genre: "Punjabi Regional", epgNo: 1920 },
  { channelNo: 641, name: "PTC News",                     hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1921 },
  { channelNo: 642, name: "News18 Punjab",                hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1922 },
  { channelNo: 643, name: "India News Punjab",            hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1923 },
  { channelNo: 644, name: "India News Haryana",           hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1924 },
  { channelNo: 645, name: "Janta TV",                     hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1925 },
  { channelNo: 646, name: "MH One News",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1926 },
  { channelNo: 647, name: "ANB News",                     hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1927 },
  { channelNo: 648, name: "Living India News",            hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1928 },
  { channelNo: 649, name: "Khabar Fast",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1930 },
  { channelNo: 650, name: "Zee Delhi NCR Haryana",        hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1931 },
  { channelNo: 651, name: "STV Haryana News",             hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1932 },
  { channelNo: 652, name: "Daily Post Punjab Haryana Himachal", hdSd: "SD", genre: "Punjabi Regional", epgNo: 1933 },
  { channelNo: 653, name: "News State Punjab Haryana Himachal", hdSd: "SD", genre: "Punjabi Regional", epgNo: 1934 },
  { channelNo: 654, name: "DD Punjabi",                   hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1935 },
  { channelNo: 655, name: "DD Himachal",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1936 },
  { channelNo: 656, name: "DD Haryana",                   hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1937 },
  { channelNo: 657, name: "PTC Chak De",                  hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1938 },
  { channelNo: 658, name: "PTC Music",                    hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1941 },
  { channelNo: 659, name: "Chardikla Time TV",            hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1945 },
  { channelNo: 660, name: "PTC Simran",                   hdSd: "SD", genre: "Punjabi Regional",       epgNo: 1946 },
  // ── Others ────────────────────────────────────────────────────
  { channelNo: 661, name: "Nepal 1",                      hdSd: "SD", genre: "Others",                 epgNo: 1951 },
  { channelNo: 662, name: "Rang",                         hdSd: "SD", genre: "Others",                 epgNo: 1952 },
  { channelNo: 663, name: "Rengoni TV",                   hdSd: "SD", genre: "Others",                 epgNo: 1953 },
  { channelNo: 664, name: "Spondon",                      hdSd: "SD", genre: "Others",                 epgNo: 1954 },
  { channelNo: 665, name: "Pear TV",                      hdSd: "SD", genre: "Others",                 epgNo: 1956 },
  { channelNo: 666, name: "Indradhanu",                   hdSd: "SD", genre: "Others",                 epgNo: 1961 },
  { channelNo: 667, name: "Jonack",                       hdSd: "SD", genre: "Others",                 epgNo: 1962 },
  { channelNo: 668, name: "DY 365",                       hdSd: "SD", genre: "Others",                 epgNo: 1970 },
  { channelNo: 669, name: "News18 Assam North East",      hdSd: "SD", genre: "Others",                 epgNo: 1971 },
  { channelNo: 670, name: "News Live",                    hdSd: "SD", genre: "Others",                 epgNo: 1973 },
  { channelNo: 671, name: "Protidin Time",                hdSd: "SD", genre: "Others",                 epgNo: 1974 },
  { channelNo: 672, name: "Prag News",                    hdSd: "SD", genre: "Others",                 epgNo: 1975 },
  { channelNo: 673, name: "North East Live",              hdSd: "SD", genre: "Others",                 epgNo: 1976 },
  { channelNo: 674, name: "NKTV Plus",                    hdSd: "SD", genre: "Others",                 epgNo: 1977 },
  { channelNo: 675, name: "Hornbill TV",                  hdSd: "SD", genre: "Others",                 epgNo: 1978 },
  { channelNo: 676, name: "ND24",                         hdSd: "SD", genre: "Others",                 epgNo: 1979 },
  { channelNo: 677, name: "NB News",                      hdSd: "SD", genre: "Others",                 epgNo: 1980 },
  { channelNo: 678, name: "Pratham Khabar 24x7",          hdSd: "SD", genre: "Others",                 epgNo: 1981 },
  { channelNo: 679, name: "NE News",                      hdSd: "SD", genre: "Others",                 epgNo: 1982 },
  { channelNo: 680, name: "DD Port Blair",                hdSd: "SD", genre: "Others",                 epgNo: 1985 },
  { channelNo: 681, name: "DD Arunprabha",                hdSd: "SD", genre: "Others",                 epgNo: 1986 },
  { channelNo: 682, name: "DD Manipur",                   hdSd: "SD", genre: "Others",                 epgNo: 1987 },
  { channelNo: 683, name: "DD North East",                hdSd: "SD", genre: "Others",                 epgNo: 1988 },
  { channelNo: 684, name: "DD Kashir",                    hdSd: "SD", genre: "Others",                 epgNo: 1989 },
  { channelNo: 685, name: "Ramdhenu",                     hdSd: "SD", genre: "Others",                 epgNo: 1990 },
  { channelNo: 686, name: "DD Meghalaya",                 hdSd: "SD", genre: "Others",                 epgNo: 1991 },
  { channelNo: 687, name: "DD Tripura",                   hdSd: "SD", genre: "Others",                 epgNo: 1992 },
  { channelNo: 688, name: "DD Mizoram",                   hdSd: "SD", genre: "Others",                 epgNo: 1993 },
  { channelNo: 689, name: "DD Nagaland",                  hdSd: "SD", genre: "Others",                 epgNo: 1994 },
  { channelNo: 690, name: "DD Goa",                       hdSd: "SD", genre: "Others",                 epgNo: 1995 },
];

module.exports = { CHANNEL_REFERENCE };